// SPDX-License-Identifier: AGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 The Mosaicast Authors

/**
 * Generates the shell's icon set from Bootstrap Icons.
 *
 * Reads `dev/icons.txt` (the whitelist) and writes two generated, committed artefacts:
 *   - `src/components/Icon.tsx` — the `<Icon>` component and the drawing for every whitelisted name.
 *   - `src/styles/icons.css`    — the PUBLIC subset as `--mc-icon-*` custom properties, which plugins
 *                                 read across the shadow boundary (ARCHITECTURE §12.3).
 *
 * `bootstrap-icons` is a devDependency, so only the whitelisted path data ever ships. The chosen
 * alternative was Font Awesome, and it was measured rather than guessed: its runtime costs ~29 kB
 * gzipped before the first icon and ~152 B per icon after, against ~103 B per icon for inlined
 * paths — the two curves diverge, so there is no icon count at which the dependency pays for itself.
 *
 * **The whole whitelist ships, used or not.** `<Icon name>` resolves its drawing at runtime, so no
 * bundler can prove a name unreachable. That is the deliberate trade for one component with a `name`
 * prop instead of an export per icon, and it is what makes `icons.txt` the budget rather than a
 * catalogue: ~100 B gzipped per line, measured at 21 icons.
 *
 * Run: `npm run icons`. CI regenerates and diffs, so a whitelist edit without a regenerate fails the
 * PR rather than landing a set that disagrees with its source.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SOURCE_DIR = join(ROOT, 'node_modules', 'bootstrap-icons', 'icons');

const SPDX_LINES = [
  'SPDX-License-Identifier: AGPL-3.0-or-later',
  'SPDX-FileCopyrightText: 2026 The Mosaicast Authors',
];

/**
 * The credit that has to travel with the artwork.
 *
 * MIT obliges the copyright notice *and* the permission notice to ship with any substantial portion
 * of the work, and minifiers strip comments — so the binding copy lives in THIRD-PARTY-NOTICES.md and
 * these headers point at it.
 */
const CREDIT_LINES = [
  '@generated by dev/gen-icons.mjs — DO NOT EDIT.',
  'Run `npm run icons` after changing dev/icons.txt.',
  '',
  'Icon artwork: Bootstrap Icons — https://icons.getbootstrap.com/',
  'Copyright (c) 2019-2024 The Bootstrap Authors, MIT License.',
  'Full licence text: THIRD-PARTY-NOTICES.md',
  '',
  'The WhatsApp and Telegram marks are trademarks of their respective owners, used here',
  'nominatively to name a share destination. No endorsement is implied.',
];

/**
 * Parses one whitelist line: `source = alias` with an optional trailing `*` marking it public.
 *
 * @param {string} line a non-empty, comment-stripped line
 * @returns {{source: string, alias: string, isPublic: boolean}}
 */
function parseEntry(line) {
  const [source, target] = line.split('=').map((part) => part.trim());
  if (!source || !target) throw new Error(`dev/icons.txt: cannot parse "${line}"`);
  return { source, alias: target.replace(/\*$/, '').trim(), isPublic: target.endsWith('*') };
}

/**
 * Reads one Bootstrap SVG and keeps only what a re-render needs.
 *
 * The `class="bi bi-*"` hook belongs to Bootstrap's own webfont CSS and would be dead weight here;
 * `width`/`height` go too, because `.mc-icon` sizes in `em` so an icon tracks the type beside it.
 *
 * @param {string} source the file name under `bootstrap-icons/icons`, without extension
 * @returns {{viewBox: string, body: string}} the viewBox and the drawing children
 */
function readDrawing(source) {
  const file = join(SOURCE_DIR, `${source}.svg`);
  let svg;
  try {
    svg = readFileSync(file, 'utf8');
  } catch {
    throw new Error(`dev/icons.txt names "${source}", which is not a Bootstrap Icons file`);
  }
  const viewBox = svg.match(/viewBox="([^"]+)"/)?.[1];
  if (!viewBox) throw new Error(`${source}.svg has no viewBox`);
  const body = svg
    .replace(/^[\s\S]*?<svg[^>]*>/, '')
    .replace(/<\/svg>[\s\S]*$/, '')
    .replace(/\s*class="[^"]*"/g, '')
    .replace(/\s+/g, ' ')
    .trim();
  return { viewBox, body };
}

/** Wraps the shared header lines in one comment syntax. */
function header(open, prefix, close) {
  const lines = [...SPDX_LINES.map((l) => `${prefix}${l}`), prefix.trimEnd(), ...CREDIT_LINES.map((l) => `${prefix}${l}`.trimEnd())];
  return [open, ...lines, close].filter((l) => l !== null).join('\n');
}

const icons = readFileSync(join(ROOT, 'dev', 'icons.txt'), 'utf8')
  .split('\n')
  .map((line) => line.replace(/#.*$/, '').trim())
  .filter(Boolean)
  .map(parseEntry)
  .map((entry) => ({ ...entry, ...readDrawing(entry.source) }));

const duplicates = icons.map((i) => i.alias).filter((alias, index, all) => all.indexOf(alias) !== index);
if (duplicates.length > 0) throw new Error(`dev/icons.txt: duplicate name(s) ${duplicates.join(', ')}`);

// ---- src/components/Icon.tsx ----

const tsx = `${header(null, '// ', null)}

/** Every icon's \`viewBox\` and drawing children, keyed by its Mosaicast name. */
const ICONS = {
${icons.map((i) => `  '${i.alias}': ['${i.viewBox}', ${JSON.stringify(i.body)}],`).join('\n')}
} as const satisfies Record<string, readonly [string, string]>;

/** Every icon the shell can draw. */
export type IconName = keyof typeof ICONS;

/**
 * A monochrome UI icon.
 *
 * Draws in \`currentColor\` and sizes in \`em\`, so it takes the colour and scale of whatever it sits
 * in and re-themes with the \`--mc-*\` tokens for free.
 *
 * **Decorative by default.** Most icons in the shell sit beside a visible label or inside a button
 * that already carries an \`aria-label\`, and announcing them again is noise — so the default is
 * \`aria-hidden\`. Pass \`label\` only where the icon is the sole carrier of meaning.
 *
 * @param name  which icon to draw
 * @param label accessible name; omit for a decorative icon
 */
export function Icon({ name, label }: { name: IconName; label?: string }) {
  const [viewBox, body] = ICONS[name];
  return (
    <svg
      className="mc-icon"
      viewBox={viewBox}
      role={label ? 'img' : undefined}
      aria-label={label}
      aria-hidden={label ? undefined : true}
      focusable="false"
      dangerouslySetInnerHTML={{ __html: body }}
    />
  );
}
`;

writeFileSync(join(ROOT, 'src', 'components', 'Icon.tsx'), tsx);

// ---- src/styles/icons.css ----

/**
 * Encodes one drawing as a data URI that survives sitting inside a CSS `url("…")`.
 *
 * @param {{viewBox: string, body: string}} icon the drawing
 * @returns {string} a `data:image/svg+xml,…` URI
 */
function dataUri({ viewBox, body }) {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${viewBox}">${body}</svg>`;
  return `data:image/svg+xml,${svg
    .replace(/"/g, "'")
    .replace(/[<>#%{}]/g, (c) => `%${c.charCodeAt(0).toString(16).toUpperCase()}`)}`;
}

const publicIcons = icons.filter((i) => i.isPublic);

const css = `${header('/*', ' * ', ' *')}
 *
 * The PUBLIC icon subset, as \`--mc-icon-*\` custom properties.
 *
 * Custom properties inherit across the shadow boundary, so a plugin's Web Component reads these
 * exactly as it reads the colour tokens (§12.3) — no SDK import, no \`platformApi\` bump, no consent
 * decision, and no version skew: a plugin built against an older SDK picks up an icon added here the
 * day it lands.
 *
 * **Use them as a mask, never as a background-image**, so the icon takes the caller's own colour and
 * re-themes with everything else:
 *
 *     .my-icon {
 *       mask-image: var(--mc-icon-close);
 *       mask-size: contain;
 *       mask-repeat: no-repeat;
 *       background: currentColor;
 *     }
 *
 * These SVGs are build-time and first-party, not uploaded assets, so §12.2's "SVG is an XSS vector"
 * does not apply to them; a masked data URI cannot execute script in any case.
 *
 * Every name below is a contract with every installed plugin: add freely, rename never.
 */
:root {
${publicIcons.map((i) => `  --mc-icon-${i.alias}: url("${dataUri(i)}");`).join('\n')}
}
`;

writeFileSync(join(ROOT, 'src', 'styles', 'icons.css'), css);

console.log(`Icon.tsx   ${icons.length} icons`);
console.log(`icons.css  ${publicIcons.length} public: ${publicIcons.map((i) => i.alias).join(' ')}`);
